# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    image: harbor-ci.cpie.io/verodin/example-voting-vote:latest
    build: ../example-voting-vote
    # use python rather than gunicorn for local dev
    command: python app.py
    depends_on:
      redis:
        condition: service_healthy 
    volumes:
     - ../example-voting-vote:/app
    ports:
      - "5000:80"

  result:
    image: harbor-ci.cpie.io/verodin/example-voting-result:latest
    build: ../example-voting-result
    # use nodemon rather than node for local dev
    command: nodemon server.js
    depends_on:
      db:
        condition: service_healthy 
    volumes:
      - ../example-voting-result:/app
    ports:
      - "5001:80"
      - "5858:5858"

  worker:
    image: harbor-ci.cpie.io/verodin/example-voting-worker:latest
    build: ../example-voting-worker
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy 
    volumes:
      - ../example-voting-worker:/app

  redis:
    image: redis:6.0.10
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    ports: ["6379"]

  db:
    image: postgres:13.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"

volumes:
  db-data:

